import type { Course } from '../../../domain/model/course';
import type { Teacher } from '../../../domain/model/teacher';
import type { Classroom } from '../../../domain/model/classroom';
import type { AcademicPeriod } from '../../../domain/model/academicPeriod';
import type { Schedule } from '../../../domain/model/schedule';
import type { Enrollment } from '../../../domain/model/enrollment';

export const MOCK_COURSES: Course[] = [
  {
    id: 'c1',
    code: 'ALG-201',
    name: 'Algoritmos II',
    credits: 4,
    weeklyHours: 4,
    requiresLab: false,
    prerequisites: [],
    maxCapacity: 30,
    isActive: true,
    careerId: 'car-1',
    semester: 3,
  },
  {
    id: 'c2',
    code: 'BD-301',
    name: 'Base de Datos',
    credits: 4,
    weeklyHours: 4,
    requiresLab: true,
    prerequisites: [],
    maxCapacity: 25,
    isActive: true,
    careerId: 'car-1',
    semester: 4,
  },
  {
    id: 'c3',
    code: 'SO-401',
    name: 'Sistemas Operativos',
    credits: 3,
    weeklyHours: 4,
    requiresLab: true,
    prerequisites: ['c1'],
    maxCapacity: 28,
    isActive: true,
    careerId: 'car-1',
    semester: 5,
  },
  {
    id: 'c4',
    code: 'RED-501',
    name: 'Redes de Computadoras',
    credits: 3,
    weeklyHours: 4,
    requiresLab: true,
    prerequisites: [],
    maxCapacity: 25,
    isActive: true,
    careerId: 'car-1',
    semester: 5,
  },
  {
    id: 'c5',
    code: 'IS-301',
    name: 'Ingeniería de Software',
    credits: 4,
    weeklyHours: 4,
    requiresLab: false,
    prerequisites: [],
    maxCapacity: 35,
    isActive: true,
    careerId: 'car-1',
    semester: 4,
  },
  {
    id: 'c6',
    code: 'IA-601',
    name: 'Inteligencia Artificial',
    credits: 3,
    weeklyHours: 4,
    requiresLab: false,
    prerequisites: ['c1'],
    maxCapacity: 30,
    isActive: true,
    careerId: 'car-1',
    semester: 6,
  },
  {
    id: 'c7',
    code: 'CAL-101',
    name: 'Cálculo Diferencial',
    credits: 5,
    weeklyHours: 4,
    requiresLab: false,
    prerequisites: [],
    maxCapacity: 40,
    isActive: true,
    careerId: 'car-1',
    semester: 1,
  },
  {
    id: 'c8',
    code: 'FIS-201',
    name: 'Física Computacional',
    credits: 3,
    weeklyHours: 4,
    requiresLab: true,
    prerequisites: [],
    maxCapacity: 30,
    isActive: true,
    careerId: 'car-1',
    semester: 2,
  },
];

export const MOCK_TEACHERS: Teacher[] = [
  {
    id: 't1',
    userId: 'user-t1',
    employeeCode: 'DOC-001',
    department: 'Ciencias de la Computación',
    maxHoursPerWeek: 20,
    qualifiedCourses: ['c1', 'c6'],
    availability: [
      { dayOfWeek: 1, startTime: '07:00', endTime: '13:00' },
      { dayOfWeek: 2, startTime: '07:00', endTime: '13:00' },
      { dayOfWeek: 3, startTime: '07:00', endTime: '13:00' },
      { dayOfWeek: 4, startTime: '07:00', endTime: '18:00' },
      { dayOfWeek: 5, startTime: '07:00', endTime: '13:00' },
    ],
  },
  {
    id: 't2',
    userId: 'user-t2',
    employeeCode: 'DOC-002',
    department: 'Ingeniería de Sistemas',
    maxHoursPerWeek: 20,
    qualifiedCourses: ['c2', 'c5'],
    availability: [
      { dayOfWeek: 1, startTime: '07:00', endTime: '18:00' },
      { dayOfWeek: 2, startTime: '14:00', endTime: '18:00' },
      { dayOfWeek: 3, startTime: '07:00', endTime: '18:00' },
      { dayOfWeek: 4, startTime: '07:00', endTime: '18:00' },
      { dayOfWeek: 5, startTime: '07:00', endTime: '18:00' },
    ],
  },
  {
    id: 't3',
    userId: 'user-t3',
    employeeCode: 'DOC-003',
    department: 'Ciencias de la Computación',
    maxHoursPerWeek: 16,
    qualifiedCourses: ['c3', 'c4'],
    availability: [
      { dayOfWeek: 1, startTime: '07:00', endTime: '18:00' },
      { dayOfWeek: 2, startTime: '07:00', endTime: '18:00' },
      { dayOfWeek: 3, startTime: '07:00', endTime: '18:00' },
      { dayOfWeek: 4, startTime: '07:00', endTime: '18:00' },
      { dayOfWeek: 5, startTime: '07:00', endTime: '18:00' },
    ],
  },
  {
    id: 't4',
    userId: 'user-t4',
    employeeCode: 'DOC-004',
    department: 'Matemáticas',
    maxHoursPerWeek: 20,
    qualifiedCourses: ['c7', 'c8'],
    availability: [
      { dayOfWeek: 1, startTime: '07:00', endTime: '18:00' },
      { dayOfWeek: 2, startTime: '07:00', endTime: '18:00' },
      { dayOfWeek: 3, startTime: '07:00', endTime: '13:00' },
      { dayOfWeek: 4, startTime: '07:00', endTime: '18:00' },
      { dayOfWeek: 5, startTime: '07:00', endTime: '18:00' },
    ],
  },
  {
    id: 't5',
    userId: 'user-t5',
    employeeCode: 'DOC-005',
    department: 'Ingeniería de Sistemas',
    maxHoursPerWeek: 20,
    qualifiedCourses: ['c1', 'c5', 'c6'],
    availability: [
      { dayOfWeek: 1, startTime: '07:00', endTime: '18:00' },
      { dayOfWeek: 2, startTime: '07:00', endTime: '18:00' },
      { dayOfWeek: 3, startTime: '07:00', endTime: '18:00' },
      { dayOfWeek: 4, startTime: '07:00', endTime: '18:00' },
      { dayOfWeek: 5, startTime: '07:00', endTime: '18:00' },
    ],
  },
];

export const MOCK_CLASSROOMS: Classroom[] = [
  {
    id: 'r1',
    name: 'Aula 101',
    building: 'Pabellón A',
    floor: 1,
    capacity: 40,
    isLab: false,
    hasProjector: true,
    isActive: true,
  },
  {
    id: 'r2',
    name: 'Aula 201',
    building: 'Pabellón A',
    floor: 2,
    capacity: 35,
    isLab: false,
    hasProjector: true,
    isActive: true,
  },
  {
    id: 'r3',
    name: 'Aula 301',
    building: 'Pabellón B',
    floor: 3,
    capacity: 45,
    isLab: false,
    hasProjector: false,
    isActive: true,
  },
  {
    id: 'r4',
    name: 'Laboratorio 101',
    building: 'Pabellón C',
    floor: 1,
    capacity: 30,
    isLab: true,
    hasProjector: true,
    isActive: true,
  },
  {
    id: 'r5',
    name: 'Laboratorio 202',
    building: 'Pabellón C',
    floor: 2,
    capacity: 28,
    isLab: true,
    hasProjector: true,
    isActive: true,
  },
];

export const MOCK_PERIODS: AcademicPeriod[] = [
  {
    id: '2026-I',
    name: '2026-I',
    isActive: true,
    minCredits: 12,
    maxCredits: 22,
  },
];

export const MOCK_SCHEDULES: Schedule[] = [];

export const MOCK_ENROLLMENTS: Enrollment[] = [];

// Helper mappings to match names for populated-like behavior
export const MOCK_TEACHER_NAMES = new Map<string, string>([
  ['t1', 'Dr. Carlos Mendoza'],
  ['t2', 'Ing. María Torres'],
  ['t3', 'Dr. Roberto Sánchez'],
  ['t4', 'Dra. Ana García'],
  ['t5', 'Ing. Pedro López'],
]);

export const MOCK_LOGS: any[] = [];
