import type { AsignacionHorario } from './tipos';

/* ============================================================
   Datos de demostración para el prototipo funcional.
   Simula la respuesta de Firestore sin necesidad de un backend real.
   ============================================================ */

export const CURSOS_DEMO = [
  {
    id: 'c1',
    codigo: 'ALG-201',
    nombre: 'Algoritmos II',
    creditos: 4,
    horasSemanales: 4,
    requiereLab: false,
    prerrequisitos: ['c0'],
    capacidadMaxima: 30,
    estaActivo: true,
    carreraId: 'car-1',
    semestre: 3,
  },
  {
    id: 'c2',
    codigo: 'BD-301',
    nombre: 'Base de Datos',
    creditos: 4,
    horasSemanales: 4,
    requiereLab: true,
    prerrequisitos: [],
    capacidadMaxima: 25,
    estaActivo: true,
    carreraId: 'car-1',
    semestre: 4,
  },
  {
    id: 'c3',
    codigo: 'SO-401',
    nombre: 'Sistemas Operativos',
    creditos: 3,
    horasSemanales: 3,
    requiereLab: true,
    prerrequisitos: ['c1'],
    capacidadMaxima: 28,
    estaActivo: true,
    carreraId: 'car-1',
    semestre: 5,
  },
  {
    id: 'c4',
    codigo: 'RED-501',
    nombre: 'Redes de Computadoras',
    creditos: 3,
    horasSemanales: 3,
    requiereLab: true,
    prerrequisitos: [],
    capacidadMaxima: 25,
    estaActivo: true,
    carreraId: 'car-1',
    semestre: 5,
  },
  {
    id: 'c5',
    codigo: 'IS-301',
    nombre: 'Ingeniería de Software',
    creditos: 4,
    horasSemanales: 4,
    requiereLab: false,
    prerrequisitos: [],
    capacidadMaxima: 35,
    estaActivo: true,
    carreraId: 'car-1',
    semestre: 4,
  },
  {
    id: 'c6',
    codigo: 'IA-601',
    nombre: 'Inteligencia Artificial',
    creditos: 3,
    horasSemanales: 3,
    requiereLab: false,
    prerrequisitos: ['c1'],
    capacidadMaxima: 30,
    estaActivo: true,
    carreraId: 'car-1',
    semestre: 6,
  },
  {
    id: 'c7',
    codigo: 'CAL-101',
    nombre: 'Cálculo Diferencial',
    creditos: 5,
    horasSemanales: 5,
    requiereLab: false,
    prerrequisitos: [],
    capacidadMaxima: 40,
    estaActivo: true,
    carreraId: 'car-1',
    semestre: 1,
  },
  {
    id: 'c8',
    codigo: 'FIS-201',
    nombre: 'Física Computacional',
    creditos: 3,
    horasSemanales: 3,
    requiereLab: true,
    prerrequisitos: [],
    capacidadMaxima: 30,
    estaActivo: true,
    carreraId: 'car-1',
    semestre: 2,
  },
];

export const DOCENTES_DEMO = [
  {
    id: 't1',
    usuarioId: 't1',
    codigoEmpleado: 'DOC-001',
    departamento: 'Ciencias de la Computación',
    maxHorasSemana: 20,
    disponibilidad: [
      { diaSemana: 1, horaInicio: '07:00', horaFin: '13:00' },
      { diaSemana: 2, horaInicio: '07:00', horaFin: '13:00' },
      { diaSemana: 3, horaInicio: '07:00', horaFin: '13:00' },
      { diaSemana: 4, horaInicio: '07:00', horaFin: '18:00' },
      { diaSemana: 5, horaInicio: '07:00', horaFin: '13:00' },
    ],
    cursosCalificados: ['c1', 'c6'],
    nombreCompleto: 'Dr. Carlos Mendoza',
  },
  {
    id: 't2',
    usuarioId: 't2',
    codigoEmpleado: 'DOC-002',
    departamento: 'Ingeniería de Sistemas',
    maxHorasSemana: 20,
    disponibilidad: [
      { diaSemana: 1, horaInicio: '07:00', horaFin: '18:00' },
      { diaSemana: 2, horaInicio: '14:00', horaFin: '18:00' },
      { diaSemana: 3, horaInicio: '07:00', horaFin: '18:00' },
      { diaSemana: 4, horaInicio: '07:00', horaFin: '18:00' },
      { diaSemana: 5, horaInicio: '07:00', horaFin: '18:00' },
    ],
    cursosCalificados: ['c2', 'c5'],
    nombreCompleto: 'Ing. María Torres',
  },
  {
    id: 't3',
    usuarioId: 't3',
    codigoEmpleado: 'DOC-003',
    departamento: 'Ciencias de la Computación',
    maxHorasSemana: 16,
    disponibilidad: [
      { diaSemana: 1, horaInicio: '07:00', horaFin: '18:00' },
      { diaSemana: 2, horaInicio: '07:00', horaFin: '18:00' },
      { diaSemana: 3, horaInicio: '07:00', horaFin: '18:00' },
      { diaSemana: 4, horaInicio: '07:00', horaFin: '18:00' },
      { diaSemana: 5, horaInicio: '07:00', horaFin: '18:00' },
    ],
    cursosCalificados: ['c3', 'c4'],
    nombreCompleto: 'Dr. Roberto Sánchez',
  },
  {
    id: 't4',
    usuarioId: 't4',
    codigoEmpleado: 'DOC-004',
    departamento: 'Matemáticas',
    maxHorasSemana: 20,
    disponibilidad: [
      { diaSemana: 1, horaInicio: '07:00', horaFin: '18:00' },
      { diaSemana: 2, horaInicio: '07:00', horaFin: '18:00' },
      { diaSemana: 3, horaInicio: '07:00', horaFin: '13:00' },
      { diaSemana: 4, horaInicio: '07:00', horaFin: '18:00' },
      { diaSemana: 5, horaInicio: '07:00', horaFin: '18:00' },
    ],
    cursosCalificados: ['c7', 'c8'],
    nombreCompleto: 'Dra. Ana García',
  },
  {
    id: 't5',
    usuarioId: 't5',
    codigoEmpleado: 'DOC-005',
    departamento: 'Ingeniería de Sistemas',
    maxHorasSemana: 20,
    disponibilidad: [
      { diaSemana: 1, horaInicio: '07:00', horaFin: '18:00' },
      { diaSemana: 2, horaInicio: '07:00', horaFin: '18:00' },
      { diaSemana: 3, horaInicio: '07:00', horaFin: '18:00' },
      { diaSemana: 4, horaInicio: '07:00', horaFin: '18:00' },
      { diaSemana: 5, horaInicio: '07:00', horaFin: '18:00' },
    ],
    cursosCalificados: ['c1', 'c5', 'c6'],
    nombreCompleto: 'Ing. Pedro López',
  },
];

export const AULAS_DEMO = [
  {
    id: 'r1',
    nombre: 'Aula 101',
    edificio: 'Bloque A',
    piso: 1,
    capacidad: 40,
    esLaboratorio: false,
    tieneProyector: true,
    estaActiva: true,
  },
  {
    id: 'r2',
    nombre: 'Aula 201',
    edificio: 'Bloque A',
    piso: 2,
    capacidad: 35,
    esLaboratorio: false,
    tieneProyector: true,
    estaActiva: true,
  },
  {
    id: 'r3',
    nombre: 'Aula 301',
    edificio: 'Bloque B',
    piso: 3,
    capacidad: 45,
    esLaboratorio: false,
    tieneProyector: false,
    estaActiva: true,
  },
  {
    id: 'r4',
    nombre: 'Laboratorio 101',
    edificio: 'Bloque C',
    piso: 1,
    capacidad: 30,
    esLaboratorio: true,
    tieneProyector: true,
    estaActiva: true,
  },
  {
    id: 'r5',
    nombre: 'Laboratorio 202',
    edificio: 'Bloque C',
    piso: 2,
    capacidad: 28,
    esLaboratorio: true,
    tieneProyector: true,
    estaActiva: true,
  },
];

export const PERIODO_DEMO = {
  id: 'p-2026-I',
  nombre: '2026-I',
  nombreVisible: 'Primer Semestre 2026',
  estaActivo: true,
  creditosMinimos: 12,
  creditosMaximos: 22,
};

/** Resultado pre-generado de demostración */
export const HORARIO_DEMO: AsignacionHorario[] = [];

export const NOMBRES_DIAS: Record<number, string> = {
  1: 'Lunes',
  2: 'Martes',
  3: 'Miércoles',
  4: 'Jueves',
  5: 'Viernes',
  6: 'Sábado',
};

export const FRANJAS_HORARIAS = [
  '07:00 - 09:00',
  '09:00 - 11:00',
  '11:00 - 13:00',
  '14:00 - 16:00',
  '16:00 - 18:00',
];
